### ISSUE TITLE
Реализовать функцию "Взятие книги"

### ISSUE THREAD

**Issue by zadokhino** [gagarin01/esdp-2016-4#25]
На странице просмотра книги есть кнопка "взять книгу". При нажатии на эту кнопку, в базе данных , а именно в таблице booking создается новая запись. 
Пример записи в базу данных:
Booking.new(user_id: id_пользователя, book_id: id_найденной книги, taken_date: дата, когда книгу взяли)
В user_id необходимо передавать id текущего пользователя(в нашем случае есть хэлпер метод - current_user)
В book_id передавать id открытой книги. 
В taken_date - фактическое время в момент нажатия кнопки - Time.now

Реализация:
1)Необходимо создать контроллер для сущности Booking:
В контроллере создать экшн, который будет создавать запись в базу данных. Для экшна лучше использовать более понятное название, например "take_book", т.к. наш контроллер будет отвечать не только за создания записи при взятии книги, но и при бронирование и продлении срока.
2)На странице отображения книги:
При нажатии на кнопку "взять книгу" - выводить флеш сообщения вверху страницы(при успешной операции - напоминание о сроке возврата книги, при ошибке - сообщение о ошибке)
Сделать изменение статуса книги(варианты: свободна, на руках) - проверять поле taken_date, если поле пустое, то книга свободна.
Если книга у кого то на руках - убрать кнопку "взять книгу". Выводить дату, когда книга должна быть возвращена. Выводить имя сотрудника и эл.почту взявшего книгу.
3) Создать метод для подсчета даты, когда книга должна быть возвращена:
По одному из требований заказчика: после взятия книги, её должны вернуть через 30 дней.
В модели Booking можно создать метод(например must_return_date), который будет к дате взятия книги прибавлять 1 месяц

-------------------------------------------------------
3 часа на раскрытие неопределенности

**Comment by Kazakbay** [comment]
Потрачено времени 5 часов
