### ISSUE TITLE
Возврат книги в библиотеку

### ISSUE THREAD

**Issue by AzamatJumabekov** [gagarin01/esdp-2016-4#27]
**Задача:**  
Пользователь может вернуть книгу, у которой заканчивается период прочтения книги. 
Для этого пользователь может нажать на кнопку "вернуть книгу" и подтвердить возврат книги
отсканировав штрих код книги штрих сканером.

**Решение:** 
Если у пользователя на руках есть книга, то на главной странице после аутентификации, необходимо отобразить кнопку "вернуть книгу". После чего в сущности `Booking` необходимо записать дату фактического возврата книги в поле `return_date` , это будет означать, что книга успешно возращена.

Возврат книги:
          

- Нажать на кнопку "вернуть книгу" на главной странице, что должно совершить переход на страницу книги, нажать на кнопку "вернуть книгу" и подтвердить возврат сканированием книги.

Так же перед возвратом книги, пользователь должен видеть только кнопку "вернуть книгу", остальные кнопки(взять книгу, забронировать) не должны быть доступны, если у пользователя уже есть книга на руках.

4 часа на реализацию задачи.

**Comment by Kazakbay** [comment]
Потрачено времени 4 часа
