### ISSUE TITLE
Подтверждение эл.почты пользователя.

### ISSUE THREAD

**Issue by zadokhino** [gagarin01/esdp-2016-4#29]
Регистрация будет осуществляться только по корпоративной почте(Уточнили у заказчика при личной встрече 24.09.16)
В модели User необходимо сделать валидацию для поля email: адрес почты должен содержать "...@beeline.kg"(Необходимо уточнить у заказчика адрес их электронной почты)
После регистрации, пользователь должен подтвердить почту. На email пользователя отправляется письмо с ссылкой для подтерждения

---

4 часа, что бы разобраться как работает отправка и подтверждение пароля
4 часа на работу
Итого: 8 часов

**Comment by AzamatJumabekov** [comment]
12 часов потрачено на ознакомление с документацией,
6 часов потрачено на реализацию функции.

Подтверждение через эл.почту работает.

**Comment by AzamatJumabekov** [comment]
Необходимо сделать валидацию email, чтобы регистрация была возможна только через домен beeline.kg. Будет реализовано после предоставления заказчиком доступа на smtp сервер Билайн.

Время на выполнение и проверку - 30 мин.
