### ISSUE TITLE
Создать flash сообщения на действия сущности booking

### ISSUE THREAD

**Issue by Kazakbay** [gagarin01/esdp-2016-4#34]
Показать flash сообщение на функцию:
 
- "взятие книги" - показать дату возврата.

- "бронирование книги" - показать что в течении 24 часа надо забрать книгу иначе бронь будет снята.

- "вернуть книгу" - Показать успешное возращение книги.

- "продление книги" - показать успешное продление и дату возрата книги.

на реализацию: 2 часа

**Comment by zadokhino** [comment]
Потрачено 30 минут
