### ISSUE TITLE
Добавить правила.

### ISSUE THREAD

**Issue by evgeniikotliarov** [gagarin01/esdp-2016-4#39]
Добавить правила пользования электронной библиотекой.
Сделать всплывающим окном с левой стороны при нажатии на окошко,   разворачиваются правила пользования библиотекой. 
Запланировано 2 часа.

Правила по использованию книг:

1) Книга предоставляется сроком до 30 дней. 
2) Вы можете продлить срок до 7 дней и только 1 раз. 
3) В случае несвоевременного возврата книги (3 раза), Вы не сможете получать их в течение 30 дней. 
4) За порчу/потерю книг, возвращается полная её стоимость.

**Comment by Esgeri** [comment]
Потрачено: 1 час.
Реализовано: 1 часа.
Итого: 2 часа.
