### ISSUE TITLE
Пагинация страниц.

### ISSUE THREAD

**Issue by zadokhino** [gagarin01/esdp-2016-4#43]
В приложении уже стоит gem will_paginate. Его назначение - разделить выводимую информацию на несколько страниц. Например: поисковые сайты на один запрос могут выводить тысячи результатов и неразумно было бы выводить весь список на одной странице.
**Задача:**
Необходимо добавить разделение страниц с помощью will_paginate на главной странице и страницах каждого отдельного жанра. В данный момент книги отображаются по 3 в ряд, на страницу будет достаточно 5 таких рядов, итого 15 книг на каждую страницу.

ссылка на документацию will_paginate: https://github.com/mislav/will_paginate

**Comment by evgeniikotliarov** [comment]
Для на чала сделал 4 книги на странице, в дальнейшем можно изменить.
