### ISSUE TITLE
Настроить ротацию(архивацию) логов на сервере

### ISSUE THREAD

**Issue by AzamatJumabekov** [gagarin01/esdp-2016-4#62]
Как известно, по мере активности на сервере растут размеры логов. Необходимо настроить ротацию логов на сервере, чтобы логи не занимали лишнее пространство на диске.
Рекомендуется использовать утилиту `logrotate`

**Comment by Kazakbay** [comment]
/home/deploy/beelibrary/shared/log/production.log {
  monthly
  size 10M
  rotate 12
  compress
  delaycompress
  notifempty
  create 644 root root
}

Это значит, что:

- утилита отслеживает файл /production.log на ежемесячной основе (интервал ротации monthly);

- **size 10M** логи будут ротироваться, как только размер файла превысит 10 М, не дожидаясь истечения срока.

- строка **rotate 12** значит, что система будет хранить логи 12 дней;

- лог-файлы можно сжимать в формат **gzip** при помощи **compress**, а **delaycompress** откладывает сжатие до следующей ротации. Обратите внимание: опция **delaycompress** будет работать, только если указана опция compress;

- **notifempty** не будет ротировать лог-файл, если он пуст;

- опция **create <режим> <владелец> <группа>** создает новый пустой файл с указанными свойствами после ротации логов.
