### ISSUE TITLE
Тестирование бронирования книги.

### ISSUE THREAD

**Issue by evgeniikotliarov** [gagarin01/esdp-2016-4#69]
Пользователь может забронировать книгу. Нужно протестировать возможность бронирования, если книга уже забронирована.

**Comment by zadokhino** [comment]
Как работает бронирование:
Кнопка бронирования доступна всегда, только меняется её функционал. Когда книга свободна, то при нажатии на кнопку "бронировать" выйдет сообщение "Ваша бронь будет снята через 24 часа" И пользователь не может взять другую книгу пока не отменит бронирования этой.
Если книга занята, то при нажатии выйдет сообщение "К сожалению книга занята. Как только освободится вам будет отправлено сообщение". В этом случае пользователь может взять другую книгу не отменяя бронирование.

**Comment by evgeniikotliarov** [comment]
Тикет закрыт, утратив актуальность.
